name: Basic Unit Testing
run-name: Basic Unit Testing
on:
  push:
    branches:
      - '*'

jobs:
  Self-hosted-unit-testing:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Unit Testing Gym
        run: |
          source ~/anaconda3/etc/profile.d/conda.sh
          conda activate CIgym
          pytest gym
      - name: Unit Testing Learning
        run: |
          source ~/anaconda3/etc/profile.d/conda.sh
          conda activate CIgym
          pytest learning

  ruff-linting:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Lint with ruff
        run: |
          source ~/anaconda3/etc/profile.d/conda.sh
          conda activate CIgym
          ruff check .